export enum QuestStatus {
	DRAFTED = "DRAFTED",
	ACTIVE = "ACTIVE",
	UPCOMING = "UPCOMING",
	COMPLETED = "COMPLETED",
	PARTICIPATED = "PARTICIPATED",
	REWARD_IN_PROGRESS = "REWARD_IN_PROGRESS",
	REWARD_COMPLETED = "REWARD_COMPLETED",
}
